### ISSUE TITLE
Laravel 6, supported?

### ISSUE THREAD

**Issue by Superme2018** [madnest/madzipper#1]
Just did an upgrade on a project:

chumper/zipper v1.0.0 requires illuminate/filesystem 5.x

**Comment by theimerj** [comment]
Hello, that is the reason why I decided to make this repo in the first place. I just semi fixed the tests, so you can run them yourself if you want. I will update them soon to correspond with phpunit and Laravel test case updates.

I am also planning to add support for new compression methods and keep this repo up to date. I hope I can get to it during the weekend and next week.

**Comment by WBDC** [comment]
@theimerj Thank you for this repo!! I literally had to change 1 line of code instead of finding a completely different alternative!

**Comment by Midstackdev** [comment]
@theimerj It doesn't Work for laravel > 6.0.

**Comment by sayanthkoroth** [comment]
> @theimerj Thank you for this repo!! I literally had to change 1 line of code instead of finding a completely different alternative!

Can you please tell me how you fixed the problem ?

**Comment by WBDC** [comment]
@sayanthkoroth What problem? 
This repo was created to support L6 as the original seems like abandoned.

**Comment by hsyir** [comment]
@theimerj   Unfortunately It doesn't Work for laravel > 6.0.

**Comment by theimerj** [comment]
Please update to v1.0.2, it resolves the issue with wrong dependency versions.
