### ISSUE TITLE
Drop Laravel requirement

### ISSUE THREAD

**Issue by BBrunekreeft** [madnest/madzipper#11]
I'd like to use this package as an alternative for the `chumper/zipper` package.
I'm not using Laravel, but since Laravel is required in composer.json, the complete Laravel Package is installed.

Is it possible to drop the Laravel requirement from composer.json, so I can use it in my own project?

**Comment by theimerj** [comment]
You know what, that is not a bad idea. I will test it tomorrow and if everything goes fine, I will drop the requirement.

**Comment by BBrunekreeft** [comment]
Any news on this. by any chance?

**Comment by theimerj** [comment]
Hello, I merged your PR #12 and made a few tweaks, so the tests run smoothly on Github Actions. I am sorry for taking so long.
