### ISSUE TITLE
Not working in PHP8

### ISSUE THREAD

**Issue by NinoSkopac** [madnest/madzipper#14]
Due to https://github.com/madnest/madzipper/blob/1bc542c1ec68091c3e5793483fa710d076f969c7/src/Madnest/Madzipper/Repositories/ZipRepository.php#L117

PHP8 thinks `file` and `stats` are named params.

**Comment by theimerj** [comment]
Thank you for your PR, I will adjust the test suite to count with PHP8.

**Comment by NinoSkopac** [comment]
Thank you for merging!!
