### ISSUE TITLE
Artisan seems to try to close the zip and the @ doesn't suppress the error

### ISSUE THREAD

**Issue by danschumann** [madnest/madzipper#29]
![image](https://user-images.githubusercontent.com/1516973/178579041-bae30508-6839-4551-bf58-538c168674c1.png)

It seems like the @ variable is used to suppress error, but in php 8.1 it doesn't seem to work anymore, or perhaps they changed the default?

![image](https://user-images.githubusercontent.com/1516973/178579187-34c59d66-763c-4d8d-b2c8-0af206a64a2c.png)

```

**Comment by danschumann** [comment]
Currently am working around the issue by overriding madzipper
```<?php

class MotoZip extends \Madnest\Madzipper\Madzipper {

  public function __destruct() {
    try {
      return parent::__destruct();
    } catch (\ValueError $er) {
      //var_dump($er, 'error'); // suppress
    }
  }
}
```

**Comment by sidneygijzen** [comment]
@danschumann the error you're getting looks a lot like the issue mentioned in #21. Perhaps the workaround posted there also works in your case without having to override Madzipper?

**Comment by scs-ben** [comment]
I basically moved your override into Madzipper: https://github.com/madnest/madzipper/pull/30

**Comment by theimerj** [comment]
Should be working with #30 until I find a more permanent solution. I am planning to rewrite the whole package anyway for v2 with more fluent API. I will open a discussion about the plan when the time comes. :)
