### ISSUE TITLE
Inconsistency on Tag 1.2.1

### ISSUE THREAD

**Issue by fpastana** [madnest/madzipper#34]
Hello guys,

I just realized that version 1.2.1 on Packagist says Madzipper is compatible with PHP ^7.3 when it accepts only PHP 7.4 or above. 

As for what I've seen, the only issue that makes it to be incompatible with PHP 7.4 is the fact the class ZipRepository has a typed property called $open. PHP 7.3 does not accept these typed variables yet, but only PHP 7.4 or above. 

`public bool $open = false;`

It could be great to fix this minor detail =).

Sincerely,
Felipe Pastana.

**Comment by repl6669** [comment]
Hello, fixed by #42. Sorry, I did not have to get to this earlier.
