### ISSUE TITLE
Laravel 11

### ISSUE THREAD

**Issue by tobiasvielmetter** [madnest/madzipper#38]
Any chance this is going to get Laravel 11 support? Thanks

**Comment by tobiasvielmetter** [comment]
Just changing the restrictions to in the `composer.json` does seem to be enough for this to work in Laravel 11.x
```
"require": {
        "php": "^8.2",
        "ext-zip": "*",
        "illuminate/support": "^11.0",
        "illuminate/filesystem": "^11.0"
    },
```

I have forked the package in the meantime to get this working again for my purposes: https://github.com/wrklst/madzipper.git

**Comment by rekul** [comment]
Above works - Please update this issue when main repo has been fixed for Laravel 11.

**Comment by repl6669** [comment]
`v1.5.0` released with support for Laravel 11. Sorry it took so long.
