### ISSUE TITLE
Not a zip archive

### ISSUE THREAD

**Issue by Hesesses** [madnest/madzipper#6]
Hi,

Is there a way to check if a file is valid zip archive?

```
$zipper = new Madzipper;
$zipper->make($filePath);
```
`Exception: Error: Failed to open /private/var/folders/23/m470jpgs09z9jwq25xg96qw80000gn/T/phpfdvQjI! Error: ZipArchive::ER_NOZIP - Not a zip archive.`

**Comment by theimerj** [comment]
Hello, you can always do something like:
```php
$zipper = new Madzipper;

try {
    $zipper->make($filePath);
} catch (Exception $e) {
    // handle the exception
}
```
Hope this helps.
